name: Publish

# trigger after merge branch "release vx.x.x" into master
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deploy:
    name: publish package
    if: ${{ startsWith(github.head_ref , 'release-v') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: debug
        run: |
          echo ${{ github.ref_name }} 
          echo ${{ github.head_ref }} 
          echo ${{ github.event.pull_request.merged }} 
          echo ${{ startsWith(github.head_ref , 'release v') }}
          echo ${{ (github.event.pull_request.merged == true) }}

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.head_ref }}
          release_name: ${{ github.head_ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
