name: Publish

# trigger after merge branch "release vx.x.x" into master
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deploy:
    name: publish package
    if: ${{ startsWith(github.head_ref , 'release-v') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: install
        run: npm ci
      
      - name: prepare
        run: npm run vscode:prepublish
      
      - name: package extension
        id: package
        run: |
          NAME=${{ github.event.repository.name }}-$(node -p "require('./package.json').version").vsix
          echo "NAME=$NAME" >> $GITHUB_OUTPUT
          npx --yes vsce package -o "./$NAME.vsix"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.txt
          name: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
          files: ${{ steps.package.outputs.NAME }}
      
      - name: Publish to Visual Studio Marketplace
        run: npx --yes vsce publish -i "./${{ steps.package.outputs.NAME }}" -p "${{ secrets.VS_MARKETPLACE_TOKEN }}"

