name: Publish

# trigger after merge branch "release vx.x.x" into master
on:
  pull_request:
    types:
      - closed
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    name: publish package
    if: ${{ startsWith(github.head_ref , 'release-v') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: install
        run: npm ci

      - name: metadata
        id: metadata
        run: |
          Version=$(node -p "require('./package.json').version")
          echo "Version=$Version" >> $GITHUB_OUTPUT
          
          ReleaseName="Release v$Version"
          echo "ReleaseName=$ReleaseName" >> $GITHUB_OUTPUT

          ReleaseTag="v$Version"
          echo "ReleaseTag=$ReleaseTag" >> $GITHUB_OUTPUT

          Package=${{ github.event.repository.name }}-$Version.vsix
          echo "Package=$Package" >> $GITHUB_OUTPUT

      - name: package extension
        id: package
        run: npx --yes vsce package -o "./${{ steps.metadata.outputs.Package }}"

      - name: Publish to Visual Studio Marketplace
        run: echo "publish complete"
        # run: npx --yes vsce publish -i "./${{ steps.metadata.outputs.Package }}" -p "${{ secrets.VS_MARKETPLACE_TOKEN }}"

      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.metadata.outputs.ReleaseTag }}

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.metadata.outputs.Package }}
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.metadata.outputs.ReleaseName }}
          tag: ${{ steps.metadata.outputs.ReleaseTag }}
