name: Release

# trigger after master merge, except release branch
on:
  pull_request:
    types:
      - closed
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: create release
    if: ${{ !startsWith(github.head_ref , 'release-v') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: update version
        id: version
        run: |
          echo "VERSION=$(npm version patch --no-git-tag-version)" >> $GITHUB_OUTPUT

      - name: Update Changelog
        run: npx --yes auto-changelog -p

      - name: release log
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "RELEASELOG<<$EOF" >> $GITHUB_ENV
          npx -y auto-changelog --stdout --release-summary -p --unreleased-only --hide-credit >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Release ${{ steps.version.outputs.VERSION }}"
          title: "Release ${{ steps.version.outputs.VERSION }}"
          labels: "release"
          body: ${{ env.RELEASELOG }}
          branch: "release-${{ steps.version.outputs.VERSION }}"
