name: Release

# trigger after master merge, except release branch
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  release:
    name: create release
    if: ${{ !startsWith(github.head_ref , 'release-v') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: debug
        run: |
          echo ${{ github.ref_name }} 
          echo ${{ github.head_ref }} 
          echo ${{ github.event.pull_request.merged }} 
          echo ${{ startsWith(github.head_ref , 'release-v') }}
          echo ${{ (github.event.pull_request.merged == true) }}

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: bump version
        id: version
        run: |
          echo "VERSION=$(npm version patch --no-git-tag-version)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Release ${{ steps.version.outputs.VERSION }}"
          title: "Release ${{ steps.version.outputs.VERSION }}"
          labels: "release"
          branch: "release-${{ steps.version.outputs.VERSION }}"